### ISSUE TITLE
Add two chapters to Study Guide

### ISSUE THREAD

**Issue by sdcastillo** [sdcastillo/PA-R-Study-Manual#19]
Hi Guanlai,

We recorded two webinars that we are adding to the study guide.  These need to be created as new subchapters and then have the Youtube video embedded.  Here is the embed code that you use in the .Rmd file.

Put this in chapter 17 under the second-level heading with the title "Writing Effectively Webinar"

---- COPY/PASTE EVERYTHING BELOW THIS LINE ---

This webinar teaches you how to write effectively.  Learn how to organize your writing, explain concepts to difference audiences, describe predictive models, and to get maximum scores on the short-answer questions.  The second half answers questions from people who took this course such as

- How are exam questions graded?

- When should I upload my documents?

- How do you interpret a logit/probit link function?

And many more!

I do appologize for the first 2 minutes of this webinar not being recorded.  I did not press the "record" button on Zoom until after I had given the introduction.  You can 

Speaker Bio
Howard Steven Friedman is a data scientist, health economist, and writer. He teaches at Columbia University and has decades of experience in the public sector, private sector and academia.

Friedman was a director at Capital One where he led teams of data scientists, statisticians, analysts and programmers in various areas of operations and marketing. He later formed private companies that provided consulting services in areas of designing, developing and modeling data touching on industries as diverse as teleco, healthcare, retail and real estate.

He has authored/co-authored about 100 scientific articles and book chapters in areas of data science, applied statistics, health economics and politics.

`<iframe width="560" height="315" src="https://www.youtube.com/embed/05Mc94aBV5U" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

**Comment by GL-Li** [comment]
You have a broken sentence:

I do appologize for the first 2 minutes of this webinar not being recorded. I did not press the "record" button on Zoom until after I had given the introduction. You can

I deleted "You can" for now. Please let me know the missing part if you had something to say. I also corrected a few typos. 

The "Speaker Bio" is shown in bold. Please check the new chapter for changes.
