### ISSUE TITLE
Extraneous code and artifacts

### ISSUE THREAD

**Issue by kevinykuo** [sdcastillo/PA-R-Study-Manual#2]
OK I took another look. I'm guessing your GitHub pages is deploying from `docs/` of `master`, since it doesn't seem like travis is active and there isn't a `gh-pages` branch. This means that you can get rid of `.travis.yml`, `_build.sh`, `_deploy.sh`, and the `book-output/` directory. You might as well set up netlify and get previews of PRs, since you're not building the book on travis.

**Comment by sdcastillo** [comment]
Correct - the book is being deployed from `master/docs` and can be viewed on https://www.exampa.net/ebook.  Signing in with an email is required.  Initially, this had been published to Bookdown.org but this will be removed.   I'll look into Netlify.  

Thanks
