### ISSUE TITLE
Search feature in R bookdown no longer working

### ISSUE THREAD

**Issue by sdcastillo** [sdcastillo/PA-R-Study-Manual#25]
Happy new year,

http://exampa.net/study-guide

The search bar is no longer working.  I used to be able to type in "glm" and would find all of the code about glms or "rpart" and the decision trees.

Please diagnose and fix.

**Comment by GL-Li** [comment]
It is not a Bookdown problem. The search works fine in the github book https://sdcastillo.github.io/PA-R-Study-Manual/. The problem is with the iframe when the book is embedded in http://exampa.net/study-guide. When was the last time the search worked in the iframe?
