### ISSUE TITLE
Remove chapters

### ISSUE THREAD

**Issue by sdcastillo** [sdcastillo/PA-R-Study-Manual#8]
Please remove these sections:

6.5 - everything that talks about tibbles.  Please replace this with data.frame lessons.
6.6 - pipes
6.7 - remove this paragraph about pipes
7.8 - exercise
- image is missing here.  Can you find out why?  I might need to get a new thumbnail
- These questions are what you are working on with the data manipulation exercise in base R

**Comment by sdcastillo** [comment]
To clarify, the study guide will still use pipes for dplyr and ggplot, however, the study guide will no longer **teach people how to use them.**

**Comment by GL-Li** [comment]
I removed tibble part of 6.5 and all of 6.6 and 6.7. Images in 7.8 are
repaired. You had several merge conflicts in your May 14 commit, which
might accidentally change some files. It will be helpful to create a branch
to work on and only merge to the master when everything is tested right.

I am not sure what to do with

   - 6.5 .... Please replace this with data.frame lessons.
   - 7.8 .... These questions are what you are working on with the data
   manipulation exercise in base R.



ᐧ
